// Datos de demo para probar la app sin Firebase

export const demoInspecciones = [
  {
    _collection: 'inspecciones',
    id: 'demo-1',
    tipo: 'general',
    areaId: 'area-1',
    areaNombre: 'Planta de Producción A',
    plantaId: 'planta-1',
    inspectorId: 'demo-user',
    inspectorNombre: 'Usuario Demo',
    fecha: new Date('2026-07-01'),
    estado: 'completada',
    hallazgos: [
      { id: 'h1', descripcion: 'Cable expuesto en zona de trabajo', categoria: 'Eléctrico', riesgo: 'alto', estado: 'abierto' },
      { id: 'h2', descripcion: 'Falta señalización de salida de emergencia', categoria: 'Señalización', riesgo: 'medio', estado: 'abierto' },
    ],
    resumen: {
      hallazgosCount: 2,
      hallazgosAbiertos: 2,
      riesgoMaximo: 'alto',
      score: 65,
    },
    observaciones: 'Se requiere atención inmediata en zona eléctrica',
    createdAt: new Date('2026-07-01'),
    updatedAt: new Date('2026-07-01'),
  },
  {
    _collection: 'inspecciones',
    id: 'demo-2',
    tipo: 'epp',
    areaId: 'area-2',
    areaNombre: 'Almacén de Materiales',
    plantaId: 'planta-1',
    inspectorId: 'demo-user',
    inspectorNombre: 'Usuario Demo',
    fecha: new Date('2026-07-05'),
    estado: 'completada',
    hallazgos: [
      { id: 'h3', descripcion: 'Trabajador sin casco en zona de carga', categoria: 'EPP', riesgo: 'medio', estado: 'cerrado' },
    ],
    resumen: {
      hallazgosCount: 1,
      hallazgosAbiertos: 0,
      riesgoMaximo: 'medio',
      score: 85,
    },
    observaciones: 'Personal requiere recordatorio de uso de EPP',
    createdAt: new Date('2026-07-05'),
    updatedAt: new Date('2026-07-05'),
  },
  {
    _collection: 'inspecciones',
    id: 'demo-3',
    tipo: 'extintores',
    areaId: 'area-1',
    areaNombre: 'Planta de Producción A',
    plantaId: 'planta-1',
    inspectorId: 'demo-user',
    inspectorNombre: 'Usuario Demo',
    fecha: new Date('2026-07-07'),
    estado: 'pendiente',
    hallazgos: [],
    resumen: {
      hallazgosCount: 0,
      hallazgosAbiertos: 0,
      riesgoMaximo: 'bajo',
      score: 100,
    },
    observaciones: '',
    createdAt: new Date('2026-07-07'),
    updatedAt: new Date('2026-07-07'),
  },
];
